// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjfvldwvbydhugxilpwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZnZsZHd2YnlkaHVneGlscHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MzkzOTcsImV4cCI6MjA3MTUxNTM5N30.vLKkuXjpj0zV_xDABDuDRefktHKBLT9hBXfXBy-h2q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});